@php($groupData = $taxPageContentData ?? [])
@if (!empty($groupData['page_content_data']))
    @foreach ($groupData['page_content_data'] as $content)
        @if (isset($content->layout))
            @if ($content->layout === 'home_banner')
                @include('partials.section.page-content.home_banner', ['content' => $content, 'groupData' => $groupData])
            @elseif ($content->layout === 'logo_section')
                @include('partials.section.page-content.logo_section', ['content' => $content, 'groupData' => $groupData])
            @elseif ($content->layout === 'customize_your_experience_section')
                @include('partials.section.page-content.customize_your_experience_section', ['content' => $content, 'groupData' => $groupData])
            @elseif ($content->layout === 'why_choose_section')
                @include('partials.section.page-content.why_choose_section', ['content' => $content, 'groupData' => $groupData])
            @elseif ($content->layout === 'review_section')
                @include('partials.section.page-content.review_section', ['content' => $content, 'groupData' => $groupData])
            @elseif ($content->layout === 'faq_section')
                @include('partials.section.page-content.faq_section', ['content' => $content, 'groupData' => $groupData])
            @elseif ($content->layout === 'two_image_with_content')
                @include('partials.section.page-content.two_image_with_content', ['content' => $content, 'groupData' => $groupData])
            @elseif ($content->layout === 'cta_bg_image_with_content')
                @include('partials.section.page-content.cta_bg_image_with_content', ['content' => $content, 'groupData' => $groupData])
            @elseif ($content->layout === 'our_most_popular_tours_section')
                @include('partials.section.page-content.our_most_popular_tours_section', ['content' => $content, 'groupData' => $groupData])
            @elseif ($content->layout === 'image_with_content')
                @include('partials.section.page-content.image_with_content', ['content' => $content, 'groupData' => $groupData])
            @elseif ($content->layout === 'what_you_will_see_section')
                @include('partials.section.page-content.what_you_will_see_section', ['content' => $content, 'groupData' => $groupData])
            @elseif ($content->layout === 'tours_section')
                @include('partials.section.page-content.tours_section', ['content' => $content, 'groupData' => $groupData])
            @elseif ($content->layout === 'inner_banner')
                @include('partials.section.page-content.inner_banner', ['content' => $content, 'groupData' => $groupData])
            @elseif ($content->layout === 'tour_section_with_load_more')
                @include('partials.section.page-content.tour_section_with_load_more', ['content' => $content, 'groupData' => $groupData])
            @elseif ($content->layout === 'image_with_content_section')
                @include('partials.section.page-content.image_with_content_section', ['content' => $content, 'groupData' => $groupData])
            @elseif ($content->layout === 'what_sets_us_apart_section')
                @include('partials.section.page-content.what_sets_us_apart_section', ['content' => $content, 'groupData' => $groupData])
            @endif
        @endif
    @endforeach
@endif
